In [1]:
import numpy as np
import random


In [2]:
dimensiones = (5,5)
estado_inicial = (0,0)
estado_objetivo=(4,4)
obstaculos = [(1,1), (1,3), (2,3), (3,0)]
acciones = [(-1,0),(1,0),(0,-1),(0,1)]

In [3]:
num_estados = dimensiones[0]*dimensiones[1]
num_estados

25

In [4]:
num_de_acciones = len(acciones)
num_de_acciones

4

In [5]:
Q = np.zeros((num_estados,num_de_acciones))
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
def estado_a_indice(estado):
    return estado[0]*dimensiones[1] + estado[1]

In [10]:
ejemplo = estado_a_indice((1,0))
ejemplo

5

In [11]:
alpha = 0.1
gamma = 0.99
epsilon = 0.2
episodios = 100


In [19]:
def indice_a_estado(number):
    filas = int(number/dimensiones[0])
    columnas = number - filas*dimensiones[1]
    return (filas,columnas)
    


In [22]:
indice_a_estado(5)

(1, 0)

In [23]:
def crear_entorno():
    dimensiones = (5,5)
    punto_inicial = (0,0)
    estado_objetivo=(4,4)
    obstaculos = [(1,1), (1,3), (2,3), (3,0)]
    return dimensiones, punto_inicial, estado_inicial, obstaculos

In [24]:
def elegir_accion(estado):
    if(random.uniform(0,1) < epsilon):
        return random.choice(range(num_de_acciones))
    else:
        return np.argmax(Q[estado_a_indice(estado)])

In [27]:
def aplicar_accion(estado,accion_idx):
    accion = acciones[accion_idx]
    nuevo_estado = tuple(np.add(estado,accion) % dimensiones)
    if nuevo_estado in obstaculos or nuevo_estado == estado:
        return estado, -100, False
    if nuevo_estado == estado_objetivo:
        return nuevo_estado, 100, True
    return nuevo_estado, -1, False

In [28]:
for episodio in range(episodios):
    estado = estado_inicial
    terminado = False
    while not terminado:
        idx_estado = estado_a_indice(estado)
        accion_idx = elegir_accion(estado)
        nuevo_estado, recompensa, terminado = aplicar_accion(estado, accion_idx)
        idx_nuevo_estado = estado_a_indice(nuevo_estado)
        
        Q[idx_estado, accion_idx] = Q[idx_estado, accion_idx] + alpha + (recompensa + gamma * np.max(Q[idx_nuevo_estado]) - Q[idx_estado, accion_idx])
        
        estado = nuevo_estado

In [29]:
politica = np.zeros(dimensiones, dtype=int)
politica

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
for i in range(dimensiones[0]):
    for j in range(dimensiones[1]):
        estado = (i,j)
        idx_estado = estado_a_indice(estado)
        mejor_accion = np.argmax(Q[idx_estado])
        politica[i,j]= mejor_accion
print("politica aprendida (0:arriba, 1:abajo, 2:izquierda, 3:derecha)")
print(politica)

politica aprendida (0:arriba, 1:abajo, 2:izquierda, 3:derecha)
[[0 0 3 3 0]
 [0 0 0 0 0]
 [0 3 1 0 2]
 [0 1 1 2 1]
 [2 2 3 3 0]]
