In [16]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler,OneHotEncoder
from sklearn.datasets import load_iris

In [2]:
data = np.array([[1,-1,2],
                [2,0,0],
                [0,1,-1]])

In [3]:
data

array([[ 1, -1,  2],
       [ 2,  0,  0],
       [ 0,  1, -1]])

In [4]:
scaler = MinMaxScaler(feature_range=(0,1))

In [5]:
data_escalada = scaler.fit_transform(data)
data_escalada

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [8]:
iris = load_iris()
X = iris.data

In [12]:
iris_escalados = scaler.fit_transform(X)
print(X[:5])
print(iris_escalados[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]


In [14]:
#standard scaler
#serveix per escalar les dades per tal que la mitja sigui 0 i la desviació standard sigui 1
scaler2 = StandardScaler()
data_escalada2 = scaler2.fit_transform(data)
data_escalada2

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [15]:
np.std(data_escalada2)

1.0

In [18]:
categorias = np.array([["rojo"],["verde"],["azul"],["verde"],["azul"]])
categorias

array([['rojo'],
       ['verde'],
       ['azul'],
       ['verde'],
       ['azul']], dtype='<U5')

In [20]:
encoder = OneHotEncoder(sparse_output = False)
data_codificada = encoder.fit_transform(categorias)
data_codificada

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])