In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])

In [3]:
array1

array([1, 2, 3])

In [4]:
array2 = np.array([[0],[10],[20],[30]])
array2

array([[ 0],
       [10],
       [20],
       [30]])

In [5]:
broadcast_suma = array2 + array1
broadcast_suma

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [6]:
broadcast_multi = array2 * array1
broadcast_multi

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [7]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
b = np.array([4,5,6])
b


array([4, 5, 6])

In [9]:
resultado = np.add(a,b)
resultado

array([5, 7, 9])

In [10]:
#.substract = resta
#.multiply
#.divide

In [11]:
resultado2 = np.exp(a)
resultado2

array([ 2.71828183,  7.3890561 , 20.08553692])

In [12]:
resultado3 = np.log(a)
resultado3

array([0.        , 0.69314718, 1.09861229])

In [14]:
resultado4 = np.sqrt(a)
resultado4

array([1.        , 1.41421356, 1.73205081])