In [1]:
import numpy as np

In [2]:
array1d = np.array([1,2,3,4,5])

In [4]:
array2d = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

In [5]:
array1d[0]

1

In [6]:
array2d[0]

array([1, 2, 3])

In [7]:
array2d[0][2]

3

In [9]:
## amb slicing
array2d[1,1]

5

In [13]:
array2d[1,1:3]

array([5, 6])

In [14]:
array2d[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])