In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    "Impares":[1,3,5],
    "Pares":[2,4,6]
})

In [3]:
df

Impares  Pares
0        1      2
1        3      4
2        5      6

In [4]:
array_np1 = df.values
array_np1

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int64)

In [5]:
array_np2 = df.to_numpy()
array_np2

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int64)

In [6]:
np.sqrt(df)

Impares     Pares
0  1.000000  1.414214
1  1.732051  2.000000
2  2.236068  2.449490

In [7]:
np.max(df)

6

In [8]:
df_desde_np = pd.DataFrame(array_np1)
df_desde_np

0  1
0  1  2
1  3  4
2  5  6

In [9]:
df_desde_np = pd.DataFrame(array_np1, columns = ["Col1", "Col2"])
df_desde_np

Col1  Col2
0     1     2
1     3     4
2     5     6

# Integración de NumPy con Pandas 1
Crea un DataFrame de Pandas llamado mi_dataframe con dos columnas: "Frutas" y "Cantidad".

La columna "Frutas" debe contener los valores "Manzana", "Banana" y "Cereza".

La columna "Cantidad" debe contener los números 5, 8 y 3 respectivamente.

Luego, convierte este DataFrame en un array de NumPy y guárdalo en una variable llamada array_frutas.

Observación:

En estos ejercicios no tendrás el botón "Ejecutar código" por esta razón no podrás visualizar los datos generados. Si deseas visualizarlos podrás servirte de un cuaderno de Jupyter y luego probar el ejercicio con ayuda del botón: "Ejecutar pruebas"

In [10]:
mi_dataframe = pd.DataFrame({
    "Frutas":["Manzana","Banana","Cereza"],
    "Cantidad":[5,8,3]
})
mi_dataframe

Frutas  Cantidad
0  Manzana         5
1   Banana         8
2   Cereza         3

In [13]:
array_frutas = mi_dataframe.to_numpy()

In [14]:
array_frutas

array([['Manzana', 5],
       ['Banana', 8],
       ['Cereza', 3]], dtype=object)

# Integración de NumPy con Pandas 2
Crea un DataFrame de Pandas llamado mi_dataframe con dos columnas: "Frutas" y "Cantidad". Identico al ejercicio anterior.

La columna "Frutas" debe contener los valores "Manzana", "Banana" y "Cereza".

La columna "Cantidad" debe contener los números 5, 8 y 3 respectivamente.

Luego, filtra las filas donde la cantidad sea mayor a 4, almacena el resultado en una variable llamada: mi_dataframe_filtrado

Convierte el resultado en un array de NumPy. Guarda el array resultante en una variable llamada array_filtrado

En esta lección podrás recordar como filtrar datos en Pandas:

Flitrado de series en Pandas

Observación:

En estos ejercicios no tendrás el botón "Ejecutar código" por esta razón no podrás visualizar los datos generados. Si deseas visualizarlos podrás servirte de un cuaderno de Jupyter y luego probar el ejercicio con ayuda del botón: "Ejecutar pruebas"

In [ ]:
mi_dataframe = pd.DataFrame({
    "Frutas":["Manzana","Banana","Cereza"],
    "Cantidad":[5,8,3]
})

In [16]:
mi_dataframe_filtrado = mi_dataframe[mi_dataframe["Cantidad"] > 4]
mi_dataframe_filtrado

Frutas  Cantidad
0  Manzana         5
1   Banana         8

In [17]:
array_filtrado = np.array(mi_dataframe_filtrado)

In [18]:
array_filtrado


array([['Manzana', 5],
       ['Banana', 8]], dtype=object)

# Integración de NumPy con Pandas 3
Crea un array de NumPy llamado mi_array con dos columnas y tres filas.



La primera columna debe contener los números 10, 20 y 30.

La segunda columna debe contener los números 40, 50 y 60.



Convierte este array en un DataFrame de Pandas llamado df_numeros y asigna los nombres "Decenas" y "Centenas" a las columnas.

In [25]:
mi_array = np.array([[10,40],[20,50],[30,60]])
mi_array

array([[10, 40],
       [20, 50],
       [30, 60]])

In [26]:
df_numeros = pd.DataFrame(mi_array,columns = ["Decenas","Centenas"])
df_numeros

Decenas  Centenas
0       10        40
1       20        50
2       30        60